apiVersion: #{akv.version}#
kind: AzureKeyVaultSecret
metadata:
  name: identity-tokens-mongo-cs
  namespace: identity
spec:
  vault:
    name: #{cosmos-db-centrico-token-manager.keyvault}#
    object:
      name: identity-tokens-mongo-cs
      type: secret
---
apiVersion: #{akv.version}#
kind: AzureKeyVaultSecret
metadata:
  name: centrico-secret
  namespace: identity
spec:
  vault:
    name: #{cosmos-db-centrico-token-manager.keyvault}#
    object:
      name: centrico-secret
      type: secret
---
apiVersion: #{akv.version}#
kind: AzureKeyVaultSecret
metadata:
  name: centrico-token-manager-uuid
  namespace: identity
spec:
  vault:
    name: #{secret-centrico-token-manager.keyvault}#
    object:
      name: centrico-token-manager-uuid
      type: secret